version: "3"

services:
    rabbitmq:
        image: "rabbitmq:3.8-management-alpine"
        ports:
            - 15672:15672
            - 5672:5672
        # volumes:
        #   - './rabbitmq_data:/var/lib/rabbitmq/mnesia'
        environment:
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
            - RABBITMQ_DEFAULT_VHOST=/
